name: Build Cheat Engine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Lazarus via Choco
      run: |
        choco install lazarus --yes

    - name: Build Cheat Engine
      run: |
        $env:PATH += ";C:\lazarus"
        cd "Cheat Engine"
        lazbuild cheatengine.lpi

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CheatEngine-Executable
        path: |
          Cheat Engine/bin/cheatengine-x86_64.exe
          Cheat Engine/bin/*.dll
